on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: robinraju/release-downloader@v1.6
        with: 
          repository: "spicyjpeg/PSn00bSDK"
          tag: "v0.21"
          fileName: "PSn00bSDK-0.21-Linux.zip"
      - name: script run line 
        run: |
          sudo apt update
          sudo apt install unzip

          unzip PSn00bSDK-0.21-Linux.zip
          mv PSn00bSDK-0.21-Linux /opt/psn00bsdk
          export PATH=$PATH:/opt/psn00bsdk/bin
          export PSN00BSDK_LIBS=/opt/psn00bsdk/lib/libpsn00b
          
          cmake -S ./tools -B ./tools/build -G "Ninja"
          cmake --build ./tools/build

          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/opt/psn00bsdk/lib/libpsn00b/cmake/sdk.cmake
          cmake --build ./build -j24
      - uses: actions/upload-artifact@v3
        with:
          name: funkin-release
          path: |
            build/funkin.bin
            build/funkin.cue

      # Runs a set of commands using the runners shell
      - name: script run line (debug)
        run: |
   
          unzip PSn00bSDK-0.21-Linux.zip
          mv PSn00bSDK-0.21-Linux /opt/psn00bsdk
          export PATH=$PATH:/opt/psn00bsdk/bin
          export PSN00BSDK_LIBS=/opt/psn00bsdk/lib/libpsn00b
          
          rm -r build

          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/opt/psn00bsdk/lib/libpsn00b/cmake/sdk.cmake -DCMAKE_BUILD_TYPE=Debug 
          cmake --build ./build -j24
      - uses: actions/upload-artifact@v3
        with:
          name: funkin-debug
          path: |
            build/funkin.bin
            build/funkin.cue
