# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
        - main
        - master
  pull_request:
    branches:
        - main
        - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: robinraju/release-downloader@v1.6
          with: 
            repository: "https://github.com/spicyjpeg/PSn00bSDK"
            latest: true
            
            # The name of the file to download.
            # Use this field only to specify filenames other than tarball or zipball, if any.
            # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
            fileName: "PSn00bSDK-0.21-Linux.zip"
            
            # Download the attached zipball (*.zip)
            zipBall: true
            
            # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
            # It will create the target directory automatically if not present
            # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
            # out-file-path: "."

      # Runs a set of commands using the runners shell
      - name: script run line 
        run: |
          sudo apt update
          sudo apt install unzip
          ls

      #- name: upload export
       # run: |
        #  curl --upload-file export.rar https://transfer.sh/  
