# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
        - main
        - master
  pull_request:
    branches:
        - main
        - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: robinraju/release-downloader@v1.6
        with: 
          repository: "spicyjpeg/PSn00bSDK"
          tag: "v0.21"
          fileName: "PSn00bSDK-0.21-Linux.zip"
      
          # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
          # It will create the target directory automatically if not present
          # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
          # out-file-path: "."

      # Runs a set of commands using the runners shell
      - name: script run line 
        run: |
          sudo apt update
          sudo apt install unzip

          unzip PSn00bSDK-0.21-Linux.zip
          mv PSn00bSDK-0.21-Linux /opt/psn00bsdk
          export PATH=$PATH:/opt/psn00bsdk/bin
          export PSN00BSDK_LIBS=/opt/psn00bsdk/lib/libpsn00b
          
          cmake -S ./tools -B ./tools/build -G "Ninja"
          cmake --build ./tools/build

          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/opt/psn00bsdk/lib/libpsn00b/cmake/sdk.cmake
          cmake --build ./build -j24
      - uses: actions/upload-artifact@v3
        with:
          name: funkin-release
          path: |
            build/funkin.bin
            build/funkin.cue

      # Runs a set of commands using the runners shell
      - name: script run line (debug)
        run: |
          rm -r build
          
          cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=/opt/psn00bsdk/lib/libpsn00b/cmake/sdk.cmake -DCMAKE_BUILD_TYPE=Debug 
          cmake --build ./build -j24
      - uses: actions/upload-artifact@v3
        with:
          name: funkin-debug
          path: |
            build/funkin.bin
            build/funkin.cue